[build]
builder = "docker"

[deploy]
releaseCommand = "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput"
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 4 auth_service.wsgi:application"
healthcheckPath = "/swagger/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
